### ISSUE TITLE
batch-size of training ImageNet

### ISSUE THREAD

**Issue by Muzijiajian** [alvinwan/neural-backed-decision-trees#10]
Hello, the current code setting in ImageNet, I can only feed batch-size=16 one gpu for resnet50 model with ImageNet database, my gpu is V100, however, the same settings in my friends computer the batch-size=36.

**Comment by alvinwan** [comment]
I unfortunately don't know the differences between your and your friend's GPUs. However, note that for ImageNet training, we use https://github.com/alvinwan/nbdt-pytorch-image-models.

**Comment by Muzijiajian** [comment]
thank u for answering.
