### ISSUE TITLE
Getting the intermediate decisions on Colab

### ISSUE THREAD

**Issue by WesDeng** [alvinwan/neural-backed-decision-trees#2]
When I call _model.forward_with_decisions_ to get the intermediate decisions on Colab, we get a list of 'node': <nbdt.data.custom.Node object at 0x7f2318a35a90> objects. How could I get access to the information within the node? And how could I generate a visualization of a decision tree based on this result?

**Comment by alvinwan** [comment]
Great questions. Thanks for using the repo!

**1. How to get information in node?**

I realized the Colab notebook by default uses the `SoftNBDT`. I suggest changing that to a `HardNBDT` instead, as `forward_with_decisions` for HardNBDT comes with more human-readable labels right off the bat.

You can also do this for SoftNBDT: Each node has an [attached synset `.synset`](https://github.com/alvinwan/neural-backed-decision-trees/blob/master/nbdt/data/custom.py#L47), and you can get the [node name from the synset `synset_to_name`](https://github.com/alvinwan/neural-backed-decision-trees/blob/master/nbdt/graph.py#L184).

**2. How to generate visualization?**

There are a number of example visualizations in the README, in [1. Hierarchies](https://github.com/alvinwan/neural-backed-decision-trees#1-hierarchies) (including how to reproduce the figures in the paper).

Let me know if you have any further questions.

**Comment by WesleyDeng1016** [comment]
Great, thanks!
