### ISSUE TITLE
Extending NBDT to the NLP domain

### ISSUE THREAD

**Issue by atreyasha** [alvinwan/neural-backed-decision-trees#7]
Hello @alvinwan and team!

First off, thank you for the awsome work. As per this repo and your paper, I noticed that the applications of the NBDT technique have been limited to images. Do you foresee this technique being used in other domains such as NLP?

I am interested in working on an interpretable decision-tree learning framework which can come close to DNNs' performance in NLP, and am drawing some inspiration from your work. Would be great to get your thoughts on this :)

**Comment by alvinwan** [comment]
@atreyasha Sorry for the late reply, and thanks for asking! Great question -- it can absolutely be applied to NLP as well. We haven't tried this ourselves (as we work in vision). However, our method and library can work for classification problems in any domain, let it be vision, NLP or otherwise.

**Comment by atreyasha** [comment]
Hi again. Thank you for the response, that is good to know :) Closing this issue.

**Comment by DesiKeki** [comment]
@alvinwan Thanks for the wonderful work on NBDT and @atreyasha Thanks for the wonderful question of using this work in the domain of NLP.
I was wondering if you guys can point me to any examples of NBDT working in NLP? 
Or give directions or any suggestions on how can I start creating one, if its not already there?

**Comment by alvinwan** [comment]
Hey @DesiKeki,

Thanks for posting! I unfortunately don't know of or have any NLP + NBDT examples. However, the code should work as-is on any classification task, including those in NLP, but for regression, here's a reply that may be helpful: https://github.com/alvinwan/neural-backed-decision-trees/issues/13.
