### ISSUE TITLE
Has this paper been published? I cannot find the information.

### ISSUE THREAD

**Issue by WhatAShot** [alvinwan/neural-backed-decision-trees#8]
Has this paper been published? I cannot find the information.

**Comment by alvinwan** [comment]
Not yet, but here's a preprint with some slightly outdated results and visualizations: https://arxiv.org/pdf/2004.00221.pdf. We'll update this repository with new results in the coming months.

**Comment by WhatAShot** [comment]
@alvinwan Okay. Actually, I read this paper a long time ago. This is an interesting work, it's amazing that it hasn't been published yet.

**Comment by alvinwan** [comment]
For anyone else landing on this page, NBDT was just accepted to ICLR 2021 yesterday; the README will soon reflect this.

(cc @WhatAShot if you're interested -- and thanks for the kind words)

**Comment by WhatAShot** [comment]
congratulations! It's really a good job!
